version: '3.8'

services:
  db:
    image: postgres:15
    container_name: snake_game_db
    environment:
      POSTGRES_DB: snake_game
      POSTGRES_USER: snake_user
      POSTGRES_PASSWORD: snake_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - snake_network

  web:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: snake_game_web
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://snake_user:snake_password@db:5432/snake_game
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    volumes:
      - ../snakes:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - snake_network

  nginx:
    image: nginx:alpine
    container_name: snake_game_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - snake_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  snake_network:
    driver: bridge
