version: '3.8'

services:
  db:
    image: postgres:15
    container_name: snake_game_db
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - snake_network

  web:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: snake_game_web
    env_file:
      - ../.env
    volumes:
      - ../snakes:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - snake_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  snake_network:
    driver: bridge
